name: Mark stale pull requests
permissions:
  issues: read
  pull-requests: write
on:
  schedule:
    - cron: "0 */6 * * *"
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          days-before-pr-stale: 7
          days-before-pr-close: 30
          stale-pr-label: inactive
          close-pr-label: auto-close
          exempt-pr-labels: keep-open
          operations-per-run: 1300
          ascending: false
          stale-pr-message: |-
            ### Inactive pull request

            This pull request has been inactive for at least **7 days**.

            > [!WARNING]
            > The pull request will automatically close after **30 days** of inactivity.

            If you are finished with your changes, don't forget to add a `#sign-off` comment to trigger pull request review.

            For more information about contributing to Microsoft Learn, see [contributor guide](https://learn.microsoft.com/contribute/).
